spring.application.name=movie-ticket-booking-system

spring.jackson.deserialization.fail-on-null-for-primitives=false

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/movie_booking_system
spring.datasource.username=postgres
spring.datasource.password=dexter@10

# Hibernate
spring.jpa.hibernate.ddl-auto=update

# SQL Logging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=true

# spring.jpa.hibernate.ddl-auto=create
